"""Add PremiumPayment model with Policy relationship

Revision ID: 0591e2018b3b
Revises: 2d7ae965b871
Create Date: 2026-07-26 01:19:06.435898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0591e2018b3b'
down_revision = '2d7ae965b871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('premium_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("payment_status IN ('PENDING', 'PAID', 'FAILED', 'PARTIAL')", name='check_premium_status_valid'),
    sa.CheckConstraint('amount > 0', name='check_premium_amount_positive'),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_reference')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('premium_payments')
    # ### end Alembic commands ###
