"""Add Claim model with Policy relationship

Revision ID: 488279284b10
Revises: 0591e2018b3b
Create Date: 2026-07-26 12:05:00.089327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '488279284b10'
down_revision = '0591e2018b3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('claim_number', sa.String(length=50), nullable=False),
    sa.Column('claim_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('claim_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'SETTLED')", name='check_claim_status_valid'),
    sa.CheckConstraint('claim_amount > 0', name='check_claim_amount_positive'),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claims')
    # ### end Alembic commands ###
