"""Add PremiumReminder model for premium due reminder tracking

Revision ID: b01fe3add8c1
Revises: d8152d085ff8
Create Date: 2026-07-27 14:46:50.899657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b01fe3add8c1'
down_revision = 'd8152d085ff8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('premium_reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('reminder_type', sa.String(length=30), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_id', 'due_date', 'reminder_type', name='uq_premium_reminder_policy_duedate_type')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('premium_reminders')
    # ### end Alembic commands ###
