"""Add Document model with Policy and User relationships

Revision ID: d8152d085ff8
Revises: 488279284b10
Create Date: 2026-07-26 13:11:58.947963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8152d085ff8'
down_revision = '488279284b10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('original_file_name', sa.String(length=255), nullable=False),
    sa.Column('stored_file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=30), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("document_type IN ('POLICY_DOCUMENT', 'ID_PROOF', 'INSURANCE_CERTIFICATE', 'CLAIM_DOCUMENT', 'OTHER')", name='check_document_type_valid'),
    sa.CheckConstraint('file_size > 0', name='check_document_file_size_positive'),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_file_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    # ### end Alembic commands ###
