"""Add fields to customers table

Revision ID: e07b53d9fb39
Revises: 1ddf7e1efe45
Create Date: 2026-07-23 13:29:10.021730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e07b53d9fb39'
down_revision = '1ddf7e1efe45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dob', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('address')
        batch_op.drop_column('dob')

    # ### end Alembic commands ###
